version: '3.9'
services:
    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB:   ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:5432"
        networks:
            - postgres_net

networks:
    postgres_net:
        driver: bridge
